services:
  app:
    container_name: WEB_CalculoProposicional
    image: node:16-slim
    command: npm run start:ssl -- --host 0.0.0.0 --poll=2000
    working_dir: /app
    ports:
        - 4200:4200
    volumes:
        - ./WEB_CalculoProposicional:/app
        # - /app/node_modules
    depends_on:
        - api

  api:
    build: API_CalculoProposicional/.
    volumes:
      - ./API_CalculoProposicional:/var/www/api
    restart: always
    networks:
      - calculo-proposicional
  nginx:
    image: nginx:latest
    container_name: calculo-proposicional-nginx
    volumes:
      - ./API_CalculoProposicional:/var/www/api
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8081:81
    depends_on:
      - api
    networks:
      - calculo-proposicional

  db:
    image: mysql:5.7.37-oracle
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: calculo_proposicional
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: logica
      MYSQL_PASSWORD: proposicional753159
    networks:
      - calculo-proposicional
networks:
  calculo-proposicional:
    driver: bridge